spring.application.name=review-service
server.port=8083

## k2 db ----
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

## stampa nel terminale le query
#spring.jpa.show-sql=true
## con create-drop diciamo a jpa di ricreare le tabelle e cancellarle quando l'app viene spenta; con update solo di aggiornarle
#spring.jpa.hibernate.ddl-auto=update

# postgreSql ----
spring.datasource.url=jdbc:postgresql://localhost:5433/reviews
spring.datasource.username=foferys
spring.datasource.password=foferys
spring.jpa.database=POSTGRESQL
spring.servlet.multipart.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
#  imposta il dialetto che deve usare
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka ---
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# zipkin - qui diciamo di tracciare ogni richiesta fatta (anche se in production non si tracciano tutte, solo 6 o meno)
management.tracing.sampling.probability=1.0