spring.application.name=company-service


#- senza optional ? l?app non parte
spring.config.import=optional:configserver:http://localhost:8080
# - ?Dammi le configurazioni per l?ambiente dev?
spring.profiles.active=company-dev

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# -- HO SPOSTATO TUTTE LE CONFIGURAZIONI NEL FILE DEL CONFIG SU GIT - queste due sopra devono rimanere sempre