spring.application.name=company-service


#- senza optional ? l?app non parte
spring.config.import=optional:configserver:http://localhost:8080
# - ?Dammi le configurazioni per l?ambiente dev?
spring.profiles.active=company-dev

# -- HO SPOSTATO TUTTE LE CONFIGURAZIONI NEL FILE DEL CONFIG SU GIT - queste due sopra devono rimanere sempre