spring.application.name=config-server

# Eureka ---
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Riferimento al repository GitHub: il Config Server lo clona,
# legge i file .yml/.properties e li espone via HTTP agli altri microservizi.
spring.cloud.config.server.git.uri=https://github.com/foferys/application-config
