spring.application.name=config-server

# Eureka ---
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#riferimento a repo github (se non indichiamo l'uri l'app non si avvia) - percHé è da li che fa il fetch delle configurazioni
spring.cloud.config.server.git.uri=https://github.com/foferys/application-config