spring.application.name=job-service
server.port=8082

## k2 db ----
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#
## stampa nel terminale le query
#spring.jpa.show-sql=true
## con create-drop diciamo a jpa di ricreare le tabelle e cancellarle quando l'app viene spenta; con update solo di aggiornarle
#spring.jpa.hibernate.ddl-auto=update

# postgreSql ----
spring.datasource.url=jdbc:postgresql://localhost:5433/job
spring.datasource.username=foferys
spring.datasource.password=foferys
spring.jpa.database=POSTGRESQL
spring.servlet.multipart.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
#  imposta il dialetto che deve usare
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka -----
# --il servizio risulta disponibile su eureka anche se non mettaimo i dati nel file perché usa
# ---quelli di default, altrimenti qui indichiamo l'url che il servizio usa per registrarsi a eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#- mettiamo true perché  deve poter registrare se stesso nel discovery
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# zipkin - qui diciamo di tracciare ogni richiesta fatta (anche se in production non si tracciano tutte, solo 6 o meno)
management.tracing.sampling.probability=1.0

# Config Server - stiamo dicendo di importare le configurazioni dal server a quell'URL (possiamo commentare la riga sopra riguardo al nome dell'applicazione)
#Questa riga dice: ?Prima di caricare le configurazioni locali, vai a chiedere al Config Server le mie configurazioni?
#- Job fa una chiamata HTTP a http://localhost:8080
#- specifica nome applicazione + profilo attivo
#- riceve le configurazioni dal repo Git
#? optional: significa:
#- se il Config Server è giù ? l?app parte lo stesso
#- senza optional ? l?app non parte
spring.config.import=optional:configserver:http://localhost:8080
# - ?Dammi le configurazioni per l?ambiente dev?
spring.profiles.active=dev