server.port=8082

## k2 db ----
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#
## stampa nel terminale le query
#spring.jpa.show-sql=true
## con create-drop diciamo a jpa di ricreare le tabelle e cancellarle quando l'app viene spenta; con update solo di aggiornarle
#spring.jpa.hibernate.ddl-auto=update

# postgreSql ----
spring.datasource.url=jdbc:postgresql://localhost:5433/job
spring.datasource.username=foferys
spring.datasource.password=foferys
spring.jpa.database=POSTGRESQL
spring.servlet.multipart.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
#  imposta il dialetto che deve usare
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect